const categorizedFonts = [
  {
    category: "Sans-serif",
    fonts: [
      { name: "Lato", fontFamily: "Lato, sans-serif" },
      { name: "Poppins", fontFamily: "Poppins, sans-serif" },
      { name: "Barlow", fontFamily: "Barlow, sans-serif" },
      { name: "Open Sans", fontFamily: "Open Sans, sans-serif" },
      { name: "Roboto", fontFamily: "Roboto, sans-serif" },
      { name: "Work Sans", fontFamily: "Work Sans, sans-serif" },
      { name: "Montserrat", fontFamily: "Montserrat, sans-serif" },
      { name: "Nunito", fontFamily: "Nunito, sans-serif" },
      { name: "Ubuntu", fontFamily: "Ubuntu, sans-serif" },
      { name: "Source Sans Pro", fontFamily: "Source Sans Pro, sans-serif" },
    ],
  },
  {
    category: "Serif",
    fonts: [
      { name: "Caudex", fontFamily: "Caudex, serif" },
      { name: "Crimson Text", fontFamily: "Crimson Text, serif" },
      { name: "Cormorant Garamond", fontFamily: "Cormorant Garamond, serif" },
      { name: "Merriweather", fontFamily: "Merriweather, serif" },
      { name: "Playfair Display", fontFamily: "Playfair Display, serif" },
      { name: "Lora", fontFamily: "Lora, serif" },
      { name: "Bitter", fontFamily: "Bitter, serif" },
      { name: "Georgia", fontFamily: "Georgia, serif" },
      { name: "Times New Roman", fontFamily: "Times New Roman, serif" },
      { name: "Libre Baskerville", fontFamily: "Libre Baskerville, serif" },
      { name: "Noto Color Emoji", fontFamily: "Noto Color Emoji" },
      { name: "Noto Emoji", fontFamily: "Noto Emoji" },
      { name: "Rubik Microbe", fontFamily: "Rubik Microbe" },
      { name: "Hanalei", fontFamily: "Hanalei" },
      { name: "Hanalei Fill", fontFamily: "Hanalei Fill" },
    ],
  },
  {
    category: "Elegant",
    fonts: [
      { name: "Love Light", fontFamily: "Love Light" },
      { name: "Flavors", fontFamily: "Flavors" },
      { name: "Rubik Wet Paint", fontFamily: "Rubik Wet Paint" },
      { name: "Forum", fontFamily: "Forum, serif" },
      { name: "Playfair Display", fontFamily: "Playfair Display, serif" },
      { name: "Kablammo", fontFamily: "Kablammo" },
      { name: "Lora", fontFamily: "Lora, serif" },
      { name: "Great Vibes", fontFamily: "Great Vibes, cursive" },
      { name: "Dancing Script", fontFamily: "Dancing Script, cursive" },
      { name: "Alex Brush", fontFamily: "Alex Brush, cursive" },
      { name: "Allura", fontFamily: "Allura, cursive" },
      { name: "Nabla", fontFamily: "Nabla" },
      { name: "Sacramento", fontFamily: "Sacramento, cursive" },
    ],
  },
  {
    category: "Casual",
    fonts: [
      { name: "Pacifico", fontFamily: "Pacifico, cursive" },
      { name: "Shadows Into Light", fontFamily: "Shadows Into Light, cursive" },
      { name: "Dancing Script", fontFamily: "Dancing Script, cursive" },
      { name: "Indie Flower", fontFamily: "Indie Flower, cursive" },
      { name: "Amatic SC", fontFamily: "Amatic SC, cursive" },
      { name: "Caveat", fontFamily: "Caveat, cursive" },
      { name: "Patrick Hand", fontFamily: "Patrick Hand, cursive" },

    ],
  },
  {
    category: "Youthful",
    fonts: [
      { name: "Fredoka", fontFamily: "Fredoka, sans-serif" },
      { name: "Chewy", fontFamily: "Chewy, cursive" },
      { name: "Comic Neue", fontFamily: "Comic Neue, cursive" },
      { name: "Baloo", fontFamily: "Baloo, cursive" },
      { name: "Bubblegum Sans", fontFamily: "Bubblegum Sans, cursive" },
      { name: "Luckiest Guy", fontFamily: "Luckiest Guy, cursive" },

    ],
  },
  {
    category: "Monospace",
    fonts: [
      { name: "Consolas", fontFamily: "Consolas, monospace" },
      { name: "Courier New", fontFamily: "Courier New, monospace" },
      { name: "Roboto Mono", fontFamily: "Roboto Mono, monospace" },
      { name: "Source Code Pro", fontFamily: "Source Code Pro, monospace" },
      { name: "Inconsolata", fontFamily: "Inconsolata, monospace" },
      { name: "Fira Code", fontFamily: "Fira Code, monospace" },

    ],
  },
  {
    category: "Handwriting",
    fonts: [
      { name: "Bradley Hand", fontFamily: "Bradley Hand, cursive" },
      { name: "Lucida Handwriting", fontFamily: "Lucida Handwriting, cursive" },
      { name: "Kalam", fontFamily: "Kalam, cursive" },
      { name: "Permanent Marker", fontFamily: "Permanent Marker, cursive" },
      { name: "Satisfy", fontFamily: "Satisfy, cursive" },
      { name: "Patrick Hand", fontFamily: "Patrick Hand, cursive" },

    ],
  },
  {
    category: "Display",
    fonts: [
      { name: "Impact", fontFamily: "Impact, sans-serif" },
      { name: "Oswald", fontFamily: "Oswald, sans-serif" },
      { name: "Anton", fontFamily: "Anton, sans-serif" },
      { name: "Bebas Neue", fontFamily: "Bebas Neue, sans-serif" },
      { name: "Fredoka One", fontFamily: "Fredoka One, cursive" },
      { name: "Archivo Black", fontFamily: "Archivo Black, sans-serif" },

    ],
  },
  {
    category: "Retro",
    fonts: [
      { name: "Special Elite", fontFamily: "Special Elite, monospace" },
      { name: "Press Start 2P", fontFamily: "'Press Start 2P', cursive" },
      { name: "Monoton", fontFamily: "Monoton, cursive" },
      { name: "Righteous", fontFamily: "Righteous, cursive" },
      { name: "Orbitron", fontFamily: "Orbitron, sans-serif" },
      { name: "VT323", fontFamily: "VT323, monospace" },
      { name: "Russo One", fontFamily: "Russo One, sans-serif" },
      { name: "Cinzel Decorative", fontFamily: "Cinzel Decorative, serif" },
      { name: "Bangers", fontFamily: "Bangers, cursive" },
      { name: "Luckiest Guy", fontFamily: "Luckiest Guy, cursive" },
    ],
  },
  {
    category: "Tech",
    fonts: [
      { name: "Orbitron", fontFamily: "Orbitron, sans-serif" },
      { name: "Audiowide", fontFamily: "Audiowide, cursive" },
      { name: "Share Tech Mono", fontFamily: "Share Tech Mono, monospace" },
      { name: "Major Mono Display", fontFamily: "Major Mono Display, monospace" },
      { name: "Share Tech Mono", fontFamily: "Share Tech Mono, monospace" },
      { name: "Chakra Petch", fontFamily: "Chakra Petch, sans-serif" }, // ✅ New font
      { name: "Russo One", fontFamily: "Russo One, sans-serif" },
      { name: "Exo 2", fontFamily: "Exo 2, sans-serif" },
      { name: "Roboto Mono", fontFamily: "Roboto Mono, monospace" },
      { name: "Fira Code", fontFamily: "Fira Code, monospace" },
      { name: "PT Mono", fontFamily: "PT Mono, monospace" },
    ],
  },
  {
    category: "Minimal",
    fonts: [
      { name: "Helvetica Neue", fontFamily: "Helvetica Neue, sans-serif" },
      { name: "Arial", fontFamily: "Arial, sans-serif" },
      { name: "Futura", fontFamily: "Futura, sans-serif" },
      { name: "Avenir", fontFamily: "Avenir, sans-serif" },
      { name: "Gill Sans", fontFamily: "Gill Sans, sans-serif" },
      { name: "Roboto", fontFamily: "Roboto, sans-serif" },
      { name: "Open Sans", fontFamily: "Open Sans, sans-serif" },
      { name: "Lato", fontFamily: "Lato, sans-serif" },
      { name: "Montserrat", fontFamily: "Montserrat, sans-serif" },
      { name: "Source Sans Pro", fontFamily: "Source Sans Pro, sans-serif" },
    ],
  },
  {
    category: "Artistic",
    fonts: [
      { name: "Brush Script MT", fontFamily: "Brush Script MT, cursive" },
      { name: "Zapfino", fontFamily: "Zapfino, cursive" },
      { name: "Papyrus", fontFamily: "Papyrus, fantasy" },
      { name: "Lobster", fontFamily: "Lobster, cursive" },
      { name: "Dawning of a New Day", fontFamily: "'Dawning of a New Day', cursive" },
      { name: "Pacifico", fontFamily: "Pacifico, cursive" },
      { name: "Great Vibes", fontFamily: "Great Vibes, cursive" },
      { name: "Sacramento", fontFamily: "Sacramento, cursive" },
      { name: "Allura", fontFamily: "Allura, cursive" },
      { name: "Alex Brush", fontFamily: "Alex Brush, cursive" },
    ],
  },
];

export default categorizedFonts;
