// productsData.js
import { BearIcon, BuildingIcon, DumbbellIcon, FlagIcon, MilitaryIcon, MusicIcon, MusieumIcon, PawIcon, ReligionIcon, RestaurantIcon, SettingsIcon, ShapesIcon, UmbrellaIcon, VectorIcon } from "../iconsSvg/CustomIcon";
import { NatureSvg } from "../iconsSvg/CustomIcon";

const aiContent = [
   {
    id: 1,
    title: "Food",
    svg: <RestaurantIcon />,
    queries: [
      "Pizza",
      "Burger",
      "Sushi",
      "Cake",
      "Ice Cream",
      "Donut",
      "Apple",
      "Banana",
      "Hot Dog",
      "Taco",
      "Sandwich",
      "Fries",
      "Steak",
      "Pasta",
      "Salad",
      "Cupcake",
      "Bread",
      "Cheese",
      "Noodles",
      "Milkshake",
      "Popcorn",
      "Coffee",
      "Tea"
    ]
  },
  {
    id: 2,
    title: "Nature",
    svg: <NatureSvg />,
    queries: ["Tree", "Leaf", "Mountain", "River", "Sun", "Cloud", "Flower", "Grass", "Beach",
      "Bubbles",
      "Camping",
      "Clouds",
      "Clover",
      "Desert",
      "Earth",
      "Fire",
      "Hiking",
      "Leaves",
      "Lightning",
      "Moon",
      "Ocean",
      "Planet",
      "Plant",
      "Rain",
      "Rainbow",

      "Rock",
      "Rose",
      "Sea",
      "Waves",

      "Space",
      "Splash",
      "Star",
      "Sky",
      "Snow",]
  },
  {
    id: 3,
    title: "Music",
    svg: <MusicIcon />,
    queries: ["Guitar", "Drum", "Music Note", "Headphones", "Violin", "Trumpet", "Band",
      "Disco",
      "Drums",
      "Hip Hop",
      "Instruments",
      "Marching Band",
      "Microphone",
      "Musical Notes",
      "Piano",
      "Punk",
      "Rap",
      "Singer"]
  },
  {
    id: 4,
    title: "Military",
    svg: <MilitaryIcon />,
    queries: ["Air Force",
      "Airplane",
      "America",
      "Anchor",
      "Armor",
      "Army",
      "Bomb",
      "Bulldog",
      "Eagle",
      "Emblem",
      "Flags",
      "Gun",
      "Helicopter",
      "Helmet",
      "Knife",
      "Map",
      "Marching",
      "Marines",
      "Mascots"]
  },
  {
    id: 5,
    title: "Designs",
    svg: <VectorIcon />,
    queries: ["Abstract", "Pattern", "Geometric", "Graffiti", "Sketch", "Line Art", "Vector", "Banners",
      "Drips",
      "Flames",
      "Shapes",
      "Speech Bubbles",
      "Swirls",
      "Wings"]
  },
  {
    id: 6,
    title: "Animals",
    svg: <PawIcon />,
    queries: [
      "Aardvark", "Alligator", "Amphibian", "Ape", "Armadillos", "Bat", "Bear", "Beaver", "Bee",
      "Bird", "Bison", "Boar", "Bobcat", "Buffalo", "Bug", "Bull", "Butterflies", "Camel", "Cat",
      "Chicken", "Clam", "Cow", "Crab", "Deer", "Dinosaur", "Dog", "Dolphin", "Donkey", "Dragon",
      "Duck", "Eagle", "Elephant", "Elk", "Fish", "Flamingo", "Fox", "Frog", "Giraffe", "Goat",
      "Gorilla", "Griffin", "Hawk", "Hippo", "Horse", "Jaguar", "Leopard", "Lion", "Lizard",
      "Monkey", "Moose", "Mouse", "Octopus", "Owl", "Panda", "Panther"
    ]
  },
  {
    id: 7,
    title: "Office",
    svg: <BuildingIcon />,
    queries: [
      "Laptop",
      "Notebook",
      "Pen",
      "Briefcase",
      "Chair",
      "Desk",
      "Coffee Mug",
      "Printer",
      "Keyboard",
      "Monitor",
      "Mouse",
      "Office Phone",
      "Whiteboard",
      "Filing Cabinet",
      "Sticky Notes",
      "Stapler",
      "Paper Clips",
      "Calendar",
      "Desk Lamp"
    ]
  },
   {
    id: 8,
    title: "Flags",
    svg: <FlagIcon />,
    queries: [
      "Aruba Flag",
      "Afghanistan Flag",
      "Angola Flag",
      "Anguilla Flag",
      "Åland Islands Flag",
      "Albania Flag",
      "Andorra Flag",
      "United Arab Emirates Flag",
      "Argentina Flag",
      "Armenia Flag",
      "Australia Flag",
      "Austria Flag",
      "Azerbaijan Flag",
      "Bahamas Flag",
      "Bahrain Flag",
      "Bangladesh Flag",
      "Barbados Flag",
      "Belarus Flag",
      "Belgium Flag",
      "Belize Flag",
      "Benin Flag",
      "Bermuda Flag",
      "Bhutan Flag",
      "Bolivia Flag",
      "Bonaire, Sint Eustatius and Saba Flag",
      "Bosnia and Herzegovina Flag",
      "Botswana Flag",
      "Bouvet Island Flag",
      "Brazil Flag",
      "British Indian Ocean Territory Flag",
      "Brunei Darussalam Flag",
      "Bulgaria Flag",
      "Burkina Faso Flag",
      "Burundi Flag",
      "Cabo Verde Flag",
      "Cambodia Flag",
      "Cameroon Flag",
      "Canada Flag",
      "Cayman Islands Flag",
      "Central African Republic Flag",
      "Chad Flag",
      "Chile Flag",
      "China Flag",
      "Christmas Island Flag",
      "Cocos (Keeling) Islands Flag",
      "Colombia Flag",
      "Comoros Flag",
      "Congo Flag",
      "Congo, Democratic Republic of the Flag",
      "Cook Islands Flag",
      "Costa Rica Flag",
      "Croatia Flag",
      "Cuba Flag",
      "Curaçao Flag",
      "Cyprus Flag",
      "Czechia Flag",
      "Côte d'Ivoire Flag",
      "Denmark Flag",
      "Djibouti Flag",
      "Dominica Flag",
      "Dominican Republic Flag",
      "Ecuador Flag",
      "Egypt Flag",
      "El Salvador Flag",
      "Equatorial Guinea Flag",
      "Eritrea Flag",
      "Estonia Flag",
      "Eswatini Flag",
      "Ethiopia Flag",
      "Falkland Islands Flag",
      "Faroe Islands Flag",
      "Fiji Flag",
      "Finland Flag",
      "France Flag",
      "French Guiana Flag",
      "French Polynesia Flag",
      "French Southern Territories Flag",
      "Gabon Flag",
      "Gambia Flag",
      "Georgia Flag",
      "Germany Flag",
      "Ghana Flag",
      "Gibraltar Flag",
      "Greece Flag",
      "Greenland Flag",
      "Grenada Flag",
      "Guadeloupe Flag",
      "Guam Flag",
      "Guatemala Flag",
      "Guernsey Flag",
      "Guinea Flag",
      "Guinea-Bissau Flag",
      "Guyana Flag",
      "Haiti Flag",
      "Heard Island and McDonald Islands Flag",
      "Holy See Flag",
      "Honduras Flag",
      "Hong Kong Flag",
      "Hungary Flag",
      "Iceland Flag",
      "India Flag",
      "Indonesia Flag",
      "Iran Flag",
      "Iraq Flag",
      "Ireland Flag",
      "Isle of Man Flag",
      "Israel Flag",
      "Italy Flag",
      "Jamaica Flag",
      "Japan Flag",
      "Jersey Flag",
      "Jordan Flag",
      "Kazakhstan Flag",
      "Kenya Flag",
      "Kiribati Flag",
      "Korea (North) Flag",
      "Korea (South) Flag",
      "Kuwait Flag",
      "Kyrgyzstan Flag",
      "Lao People's Democratic Republic Flag",
      "Latvia Flag",
      "Lebanon Flag",
      "Lesotho Flag",
      "Liberia Flag",
      "Libya Flag",
      "Liechtenstein Flag",
      "Lithuania Flag",
      "Luxembourg Flag",
      "Macao Flag",
      "Madagascar Flag",
      "Malawi Flag",
      "Malaysia Flag",
      "Maldives Flag",
      "Mali Flag",
      "Malta Flag",
      "Marshall Islands Flag",
      "Martinique Flag",
      "Mauritania Flag",
      "Mauritius Flag",
      "Mayotte Flag",
      "Mexico Flag",
      "Micronesia Flag",
      "Moldova Flag",
      "Monaco Flag",
      "Mongolia Flag",
      "Montenegro Flag",
      "Montserrat Flag",
      "Morocco Flag",
      "Mozambique Flag",
      "Myanmar Flag",
      "Namibia Flag",
      "Nauru Flag",
      "Nepal Flag",
      "Netherlands Flag",
      "New Caledonia Flag",
      "New Zealand Flag",
      "Nicaragua Flag",
      "Niger Flag",
      "Nigeria Flag",
      "Niue Flag",
      "Norfolk Island Flag",
      "North Macedonia Flag",
      "Northern Mariana Islands Flag",
      "Norway Flag",
      "Oman Flag",
      "Pakistan Flag",
      "Palau Flag",
      "Palestine Flag",
      "Panama Flag",
      "Papua New Guinea Flag",
      "Paraguay Flag",
      "Peru Flag",
      "Philippines Flag",
      "Pitcairn Flag",
      "Poland Flag",
      "Portugal Flag",
      "Puerto Rico Flag",
      "Qatar Flag",
      "Réunion Flag",
      "Romania Flag",
      "Russia Flag",
      "Rwanda Flag",
      "Saint Barthélemy Flag",
      "Saint Helena Flag",
      "Saint Kitts and Nevis Flag",
      "Saint Lucia Flag",
      "Saint Martin Flag",
      "Saint Pierre and Miquelon Flag",
      "Saint Vincent and the Grenadines Flag",
      "Samoa Flag",
      "San Marino Flag",
      "Sao Tome and Principe Flag",
      "Saudi Arabia Flag",
      "Senegal Flag",
      "Serbia Flag",
      "Seychelles Flag",
      "Sierra Leone Flag",
      "Singapore Flag",
      "Sint Maarten Flag",
      "Slovakia Flag",
      "Slovenia Flag",
      "Solomon Islands Flag",
      "Somalia Flag",
      "South Africa Flag",
      "South Georgia and the South Sandwich Islands Flag",
      "South Sudan Flag",
      "Spain Flag",
      "Sri Lanka Flag",
      "Sudan Flag",
      "Suriname Flag",
      "Svalbard and Jan Mayen Flag",
      "Sweden Flag",
      "Switzerland Flag",
      "Syrian Arab Republic Flag",
      "Taiwan Flag",
      "Tajikistan Flag",
      "Tanzania Flag",
      "Thailand Flag",
      "Timor-Leste Flag",
      "Togo Flag",
      "Tokelau Flag",
      "Tonga Flag",
      "Trinidad and Tobago Flag",
      "Tunisia Flag",
      "Turkey Flag",
      "Turkmenistan Flag",
      "Tuvalu Flag",
      "Uganda Flag",
      "Ukraine Flag",
      "United Kingdom Flag",
      "United States Flag",
      "Uruguay Flag",
      "Uzbekistan Flag",
      "Vanuatu Flag",
      "Venezuela Flag",
      "Viet Nam Flag",
      "Western Sahara Flag",
      "Yemen Flag",
      "Zambia Flag",
      "Zimbabwe Flag"
    ]


  },
  {
    id: 9,
    title: "Greek",
    svg: <MusieumIcon />,
    queries: [
      "Greek Temple",
      "Athena",
      "Olive Wreath",
      "Greek Vase",
      "Spartan",
      "Hercules",
      "Greek Columns",
      "Greek God",
      "Zeus",
      "Apollo",
      "Olympus",
      "Ancient Greece",
      "Greek Helmet",
      "Philosopher",
      "Socrates",
      "Greek Warrior",
      "Acropolis",
      "Greek Mythology"
    ]
  }
  ,
  {
    id: 10,
    title: "Sports",
    svg: <DumbbellIcon />,
    queries: [
      "Football",
      "Basketball",
      "Tennis",
      "Running",
      "Gym",
      "Dumbbell",
      "Cricket",
      "Swimming",
      "Cycling",
      "Baseball",
      "Volleyball",
      "Yoga",
      "Martial Arts",
      "Boxing",
      "Skateboarding"
    ]
  },

  {
    id: 11,
    title: "Mascots",
    svg: <BearIcon />,
    queries: [
      "Lion",
      "Tiger",
      "Eagle",
      "Panther",
      "Wolf",
      "Bear",
      "Falcon",
      "Shark",
      "Dragon",
      "Bull",
      "Hawk",
      "Cheetah",
      "Rhino",
      "Jaguar",
      "Griffin"
    ]
  },

  {
    id: 12,
    title: "Jobs",
    svg: <SettingsIcon />,
    queries: [
      "Doctor",
      "Engineer",
      "Chef",
      "Teacher",
      "Pilot",
      "Firefighter",
      "Nurse",
      "Artist",
      "Photographer",
      "Scientist",
      "Lawyer",
      "Mechanic",
      "Architect",
      "Journalist",
      "Dentist"
    ]
  },

  {
    id: 13,
    title: "Holidays",
    svg: <UmbrellaIcon />,
    queries: [
      "Beach",
      "Umbrella",
      "Palm Tree",
      "Travel",
      "Suitcase",
      "Sun",
      "Sunglasses",
      "Cocktail",
      "Sandcastle",
      "Sunset",
      "Flip Flops",
      "Surfboard",
      "Tropical",
      "Resort",
      "Vacation"
    ]
  },

  {
    id: 14,
    title: "Shapes",
    svg: <ShapesIcon />,
    queries: [
      "Circle",
      "Square",
      "Triangle",
      "Star",
      "Hexagon",
      "Polygon",
      "Rectangle",
      "Oval",
      "Diamond",
      "Pentagon",
      "Arrow",
      "Heart",
      "Crescent",
      "Cross",
      "Parallelogram"
    ]
  },

  {
    id: 15,
    title: "Religion",
    svg: <ReligionIcon />,
    queries: [
      "Cross",
      "Crescent",
      "Om",
      "Star of David",
      "Yin Yang",
      "Temple",
      "Prayer Hands",
      "Buddha",
      "Church",
      "Mosque",
      "Torah",
      "Lotus",
      "Mandala",
      "Rosary",
      "Angel"
    ]
  }

];




export { aiContent };

