const mongoose = require("mongoose");



const SSProductMapping = new mongoose.Schema({
  sku: { type: String, required: true },
  gtin: String,
  skuID_Master: Number,
  yourSku: String,
  styleID: { type: Number, required: true },
  brandName: String,
  brandID: String,
  styleName: String,
  colorName: String,
  colorCode: String,
  colorPriceCodeName: String,
  colorGroup: String,
  colorGroupName: String,
  colorFamilyID: String,
  colorFamily: String,
  baseCategoryID: String,
  colorSwatchImage: String,
  colorSwatchTextColor: String,
  colorFrontImage: String,
  colorSideImage: String,
  colorBackImage: String,
  colorDirectSideImage: String,
  colorOnModelFrontImage: String,
  colorOnModelSideImage: String,
  colorOnModelBackImage: String,
  color1: String,
  color2: String,
  sizeName: String,
  sizeCode: String,
  sizeOrder: String,
  sizePriceCodeName: String,
  caseQty: Number,
  unitWeight: Number,
  mapPrice: Number,
  piecePrice: Number,
  dozenPrice: Number,
  casePrice: Number,
  salePrice: Number,
  customerPrice: Number,
  saleExpiration: Date,
  noeRetailing: Boolean,
  caseWeight: Number,
  caseWidth: Number,
  caseLength: Number,
  caseHeight: Number,
  polyPackQty: Number,
  qty: Number,
  countryOfOrigin: String,
  warehouses: { type: [Object], default: [] },

  shopifyProductId: { type: String, default: null },
  shopifyProductData: { type: Object, default: null },
  shopifyVariantId: { type: String, default: null },
  shopifyInventoryId: { type: String, default: null },
  shopifyInventoryStatus: { type: String, default: "pending" },
  shopifyDataUpdateStatus: { type: String, default: "pending" },
  error: { type: String, default: null },
  specs: [
    {
      specName: { type: String, required: true },
      value: { type: String, required: true },
    }
  ],
}, { timestamps: true });

module.exports = mongoose.model("SSProductMapping", SSProductMapping);
